name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build . --file Dockerfile --tag su77ungr/casalioy:stable
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          docker push su77ungr/casalioy:stable
